clean: true
sdk: iphone
#swift_version: 5.0.0
author: Mike Martyniuk
github_url: https://github.com/Lon03/SocialAnimalHelper
module: SocialAnimalHelper
module_version: 1.1.1
copyright: "2019-present. See LICENSE for more details."
xcodebuild_arguments: [clean,build,-project,SocialAnimalHelper.xcodeproj,-scheme,SocialAnimalHelper]
min_acl: internal
